image: node:alpine

stages:
  - test
  - build
  - publish

variables:
  GIT_DEPTH: 1

cache:
  key: npm
  paths:
    - .npm/

test:
  stage: test
  script:
    - npm config set cache "$(pwd)/.npm"
    - npm ci --no-audit --prefer-offline
    - node run test -cp
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - node run build
  dependencies:
    - test
  artifacts:
    paths:
      - build/
      - node_modules/
  only:
    - tags

publish:
  stage: publish
  script:
    - node run publish
  dependencies:
    - build
  artifacts:
    paths:
      - node_modules/
  only:
    - tags
