image: node:alpine

variables:
  GIT_DEPTH: "3"

run:
  script:
    - npm ci
    - node run test -cp
    - node run build
    - if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then echo "publish"; fi
