version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm_cache_{{ checksum "package-lock.json" }}
          - npm_cache
      - run: npm install
      - save_cache:
          paths:
            - ~/.npm
          key: npm_cache_{{ checksum "package-lock.json" }}
      - run: node run circleci
      - run: |
          if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
            node run npm publish
          fi
