version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn_cache_{{ checksum "yarn.lock" }}
          - yarn_cache
      - run: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn_cache_{{ checksum "yarn.lock" }}
      - run: node run circleci
      - run: |
          if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
            node run npm publish
          fi
