name: Publish

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish release to npm
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          key: cache-Ubuntu-14-${{ hashFiles('package-lock.json') }}
          path: ./node_modules

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Ensure tests pass and then publish build to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: node run test + build + publish
