name: Publish

on:
  pull_request:
    branches:
      - main
    types:
      - closed

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          key: cache-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          path: |
            ~/npm_cache
            ./node_modules

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm config set cache ~/.npm-cache
          npm ci --no-audit --prefer-offline

      - name: Tag commit push it to Github
        run: |
          git config --global user.name "Github Action Bot"
          git config --global user.email "<>"
          VERSION=`python -m poetry version -s`
          git tag -a "v$VERSION" -m "Version $VERSION"
          git push --follow-tags

      - name: Publish release to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m poetry config pypi-token.pypi $PYPI_TOKEN
          python -m poetry publish --build
