name: Publish

on:
  pull_request:
    branches:
      - main
    types:
      - closed

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          key: cache-Ubuntu-14-${{ hashFiles('package-lock.json') }}
          path: |
            ~/npm_cache
            ./node_modules

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm config set cache ~/.npm-cache
          npm ci --no-audit --prefer-offline

      - name: Tag commit and push it to Github, build release and publish it to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "Github Action Bot"
          git config --global user.email "<>"
          node run publish
