name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
      - 'release/*'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Tests on ${{ matrix.os }} with node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [MacOS]
        node-version: [14]
        run-all:
          - ${{ contains(github.ref, 'main') || contains(github.ref, 'release') }}
        exclude:
          - run-all: false
            os: Ubuntu
            node-version: 10
          - run-all: false
            os: Ubuntu
            node-version: 12
          - run-all: false
            os: MacOS
          - run-all: false
            os: Windows
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Setup cache
      #  uses: actions/cache@v2
      #  id: cache
      #  with:
      #    key: cache-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      #    path: node_modules

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run tests
        run: node run test
